/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing Pharo errors from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_PharoApplicationException,
  SWIG_PharoArithmeticException,
  SWIG_PharoDivideByZeroException,
  SWIG_PharoIndexOutOfRangeException,
  SWIG_PharoInvalidCastException,
  SWIG_PharoInvalidOperationException,
  SWIG_PharoIOException,
  SWIG_PharoNullReferenceException,
  SWIG_PharoOutOfMemoryException,
  SWIG_PharoOverflowException,
  SWIG_PharoSystemException
} SWIG_PharoExceptionCodes;

typedef enum {
  SWIG_PharoArgumentException,
  SWIG_PharoArgumentNullException,
  SWIG_PharoArgumentOutOfRangeException
} SWIG_PharoExceptionArgumentCodes;

static SWIG_PharoExceptionCodes SWIG_PharoPendingExceptionCode;
static const char* SWIG_PharoPendingExceptionMsg;

static void SWIGUNUSED SWIG_PharoSetPendingException(SWIG_PharoExceptionCodes code, const char *msg) {
    SWIG_PharoPendingExceptionCode = code;
    SWIG_PharoPendingExceptionMsg = msg;
}

static void SWIGUNUSED SWIG_PharoSetPendingExceptionArgument(SWIG_PharoExceptionArgumentCodes code, const char *msg, const char *param_name) {
    // TODO:
}

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT SWIG_PharoExceptionCodes SWIGSTDCALL SWIG_PharoGetPendingExceptionCode() {
  return SWIG_PharoPendingExceptionCode;
}

SWIGEXPORT const char *SWIGSTDCALL SWIG_PharoGetPendingExceptionMessage() {
  return SWIG_PharoPendingExceptionMsg;
}

char *SWIG_csharp_string_callback(const char *s)
{
    return (char*)s;
}

#ifdef __cplusplus
}
#endif



extern int    gcd(int x, int y);
extern double Foo;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int PharoNB_gcd(int nbarg1, int nbarg2) {
  int nbresult ;
  int arg1 ;
  int arg2 ;
  int result;
  
  arg1 = (int)nbarg1; 
  arg2 = (int)nbarg2; 
  result = (int)gcd(arg1,arg2);
  nbresult = result; 
  return nbresult;
}


SWIGEXPORT void PharoNB_Foo_set(double nbarg1) {
  double arg1 ;
  
  arg1 = (double)nbarg1; 
  Foo = arg1;
}


SWIGEXPORT double PharoNB_Foo_get() {
  double nbresult ;
  double result;
  
  result = (double)Foo;
  nbresult = result; 
  return nbresult;
}


#ifdef __cplusplus
}
#endif

